foreground         #c2c0c1
background         #0c0507
background_opacity 1.0
cursor             #c2c0c1

active_tab_foreground     #0c0507
active_tab_background     #c2c0c1
inactive_tab_foreground   #c2c0c1
inactive_tab_background   #0c0507

active_border_color   #c2c0c1
inactive_border_color #0c0507
bell_border_color     #CE971E

color0       #0c0507
color8       #675558
color1       #CE971E
color9       #CE971E
color2       #6F21A5
color10      #6F21A5
color3       #2C6995
color11      #2C6995
color4       #A221C6
color12      #A221C6
color5       #CF12DB
color13      #CF12DB
color6       #FA04FA
color14      #FA04FA
color7       #c2c0c1
color15      #c2c0c1
