foreground         #c4c1c3
background         #150910
background_opacity 1.0
cursor             #c4c1c3

active_tab_foreground     #150910
active_tab_background     #c4c1c3
inactive_tab_foreground   #c4c1c3
inactive_tab_background   #150910

active_border_color   #c4c1c3
inactive_border_color #150910
bell_border_color     #5E3C3F

color0       #150910
color8       #6c5863
color1       #5E3C3F
color9       #5E3C3F
color2       #655450
color10      #655450
color3       #A2493C
color11      #A2493C
color4       #956656
color12      #956656
color5       #C4946F
color13      #C4946F
color6       #866F91
color14      #866F91
color7       #c4c1c3
color15      #c4c1c3
