foreground         #c6c6c8
background         #1e1b25
background_opacity 1.0
cursor             #c6c6c8

active_tab_foreground     #1e1b25
active_tab_background     #c6c6c8
inactive_tab_foreground   #c6c6c8
inactive_tab_background   #1e1b25

active_border_color   #c6c6c8
inactive_border_color #1e1b25
bell_border_color     #1A4393

color0       #1e1b25
color8       #686278
color1       #1A4393
color9       #1A4393
color2       #2C538E
color10      #2C538E
color3       #2D5EA1
color11      #2D5EA1
color4       #506F9D
color12      #506F9D
color5       #648BB0
color13      #648BB0
color6       #539BCE
color14      #539BCE
color7       #c6c6c8
color15      #c6c6c8
