print_info() {
  prin "$(color 1)┌───────────────────────────────────────────────────────┐"
  info "${c4} Name " title
  prin "$(color 1)└───────────────────────────────────────────────────────┘"
  prin "$(color 1)   $(color 2)    $(color 3)    $(color 4)    $(color 5)    $(color 6)    $(color 7)    $(color 8)    $(color 1)  \n \n $(color 9) \n   $(color 10)    $(color 11)    $(color 12)    $(color 13)    $(color 14)    $(color 15)    $(color 16)    $(color 9)    "
  prin "$(color 1)┌───────────────────────────────────────────────────────┐"
  info "${c1} OS" os
  info "${c1}│ ├ " distro
  info "${c1}│ ├ " kernel
  #  info "${c1}│ ├󰏗 " packages
  info "${c1}│ └ " shell
  prin"│"
  info "${c2} DE/WM" wm
  info "${c2}│ ├󰂫 " theme
  info "${c2}│ ├󰂫 " icons
  info "${c2}│ └ " term
  prin"│"
  info "${c3} PC" model
  info "${c3}│ ├󰅐 " uptime
  info "${c3}│ ├ " memory
  info "${c3}│ └ " resolution
  info "${c3}│ ├󰍹 " gpu
  info "${c3}│ ├󰍛 " cpu
  prin "$(color 3)└────────────────────────────────────────────────────────┘"
  echo
  prin "$(color 1)   $(color 2)    $(color 3)    $(color 4)    $(color 5)    $(color 6)    $(color 7)    $(color 8)    $(color 1)  \n \n $(color 9) \n   $(color 10)    $(color 11)    $(color 12)    $(color 13)    $(color 14)    $(color 15)    $(color 16)    $(color 9)    "
}
title_fqdn="off"
kernel_shorthand="on"
distro_shorthand="on"
os_arch="on"
uptime_shorthand="on"
memory_percent="off"
memory_unit="mib"
package_managers="on"
shell_path="off"
shell_version="on"
speed_type="bios_limit"
speed_shorthand="off"
cpu_brand="on"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="on"
gpu_brand="on"
gpu_type="all"
refresh_rate="off"
gtk_shorthand="off"
gtk2="on"
gtk3="on"
public_ip_host="http://ident.me"
public_ip_timeout=2
de_version="on"
disk_show=('/')
disk_subtitle="mount"
disk_percent="on"
music_player="auto"
song_format="%artist% - %album% - %title%"
song_shorthand="off"
mpc_args=()
colors=(distro)
bold="on"
underline_enabled="on"
underline_char="󰍴"
separator="->"
block_range=(0 15)
color_blocks="on"
block_width=3
block_height=1
col_offset="auto"
bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
cpu_display="off"
memory_display="off"
battery_display="off"
disk_display="off"
image_backend="ascii"
image_source="auto"
ascii_distro="auto"
ascii_colors=(1 2 3 4 5 6 7 8)
ascii_bold="on"
image_loop="off"
thumbnail_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="auto"
gap=2
yoffset=0
xoffset=0
background_color=
stdout="off"
