alias nrs='~/dotfiles/scripts/git_updater.sh && sudo nixos-rebuild switch --flake ~/dotfiles/nixos'
alias up='~/dotfiles/scripts/updatesys_Nixos.sh'
alias windows='~/dotfiles/scripts/Boot-Windows10.sh'
alias total='gu && up'
alias ls='eza -a --tree -L 1'
alias zellij='zellij -l welcome'
alias emacs='emacs -nw'
alias y='yazi'