format = """
~❯
"""

right_format = """
$time
"""


[localip]
disabled = true
ssh_only = false
format = '[$localipv4](bold red) '

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = '[$hostname](bold red) '
trim_at = "."
disabled = false

[git_branch]
disabled = false

[git_status]
disabled = true

[env_var]
disabled = true

[shell]
disabled = false

[rust]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[dotnet]
disabled = true


#[character] # The name of the module we are configuring is "character"
#success_symbol = "[](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
#error_symbol = "[✗](bold red)"
#  

# configure directory
[directory]
#read_only = " "
truncation_length = 1
truncate_to_repo = false   # truncates directory to root folder if in github repo
style = "bold italic blue"
disabled = true

[cmd_duration]
min_time = 4
show_milliseconds = true
disabled = true
style = "bold italic red"

[time]
disabled = true
format = '[$time]($style)'
time_format = '%T'
utc_time_offset = '+1'
time_range = '00:00:00-23:59:59'

[shlvl]
symbol = " "
