[config]

[config.wallpaper]
set = true
command = "swww img --transition-type center {{ image }}"

#[templates.kitty]
#input_path = '~/.config/matugen/templates/kitty.conf'
#output_path = '~/.config/kitty/matugen.conf'
#post_hook = 'pkill -SIGUSR1 kitty'


[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'


[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/matugen.css'
