# pywal theme for ghostty

background = 0c0c1b
foreground = c2c2c6
cursor-color = c2c2c6
selection-background = c2c2c6
selection-foreground = 0c0c1b

palette = 0=#0c0c1b
palette = 1=#B32071
palette = 2=#99A06F
palette = 3=#1C498D
palette = 4=#A50292
palette = 5=#FC0A88
palette = 6=#F423A4
palette = 7=#c2c2c6
palette = 8=#5b5b6f
palette = 9=#B32071
palette = 10=#99A06F
palette = 11=#1C498D
palette = 12=#A50292
palette = 13=#FC0A88
palette = 14=#F423A4
palette = 15=#c2c2c6
