# pywal theme for ghostty

background = 101d25
foreground = c3c6c8
cursor-color = c3c6c8
selection-background = c3c6c8
selection-foreground = 101d25

palette = 0=#101d25
palette = 1=#AC6D98
palette = 2=#EC748A
palette = 3=#DA77A4
palette = 4=#5EA1A3
palette = 5=#51BDA4
palette = 6=#78B1DA
palette = 7=#c3c6c8
palette = 8=#5f6d74
palette = 9=#AC6D98
palette = 10=#EC748A
palette = 11=#DA77A4
palette = 12=#5EA1A3
palette = 13=#51BDA4
palette = 14=#78B1DA
palette = 15=#c3c6c8
