# pywal theme for ghostty

background = 0c1d1d
foreground = c2c6c6
cursor-color = c2c6c6
selection-background = c2c6c6
selection-foreground = 0c1d1d

palette = 0=#0c1d1d
palette = 1=#818E7A
palette = 2=#75918C
palette = 3=#92A79D
palette = 4=#93B1AC
palette = 5=#A7C4BA
palette = 6=#A3C7C4
palette = 7=#c2c6c6
palette = 8=#5c7070
palette = 9=#818E7A
palette = 10=#75918C
palette = 11=#92A79D
palette = 12=#93B1AC
palette = 13=#A7C4BA
palette = 14=#A3C7C4
palette = 15=#c2c6c6
