source = ./usual.conf
source = ./layout.conf
source = ./windoweffects.conf
source = ./appearance.conf
source = ./keybinds.conf
exec = bash ~/dotfiles/nixos/modules/hosts/users/nixboom/home/scripts/autostart/autostart.sh


xwayland_persistence = 1