# pywal theme for ghostty

background = 121522
foreground = c3c4c7
cursor-color = c3c4c7
selection-background = c3c4c7
selection-foreground = 121522

palette = 0=#121522
palette = 1=#465A67
palette = 2=#66416C
palette = 3=#4C6372
palette = 4=#6C6C6C
palette = 5=#45628E
palette = 6=#60849B
palette = 7=#c3c4c7
palette = 8=#5e6274
palette = 9=#465A67
palette = 10=#66416C
palette = 11=#4C6372
palette = 12=#6C6C6C
palette = 13=#45628E
palette = 14=#60849B
palette = 15=#c3c4c7
