# pywal theme for ghostty

background = 0d0d1f
foreground = c2c2c7
cursor-color = c2c2c7
selection-background = c2c2c7
selection-foreground = 0d0d1f

palette = 0=#0d0d1f
palette = 1=#674D5F
palette = 2=#444A6A
palette = 3=#A9686E
palette = 4=#556D94
palette = 5=#E77691
palette = 6=#45ADD2
palette = 7=#c2c2c7
palette = 8=#5c5c71
palette = 9=#674D5F
palette = 10=#444A6A
palette = 11=#A9686E
palette = 12=#556D94
palette = 13=#E77691
palette = 14=#45ADD2
palette = 15=#c2c2c7
