# pywal theme for ghostty

background = 0a0a17
foreground = c1c1c5
cursor-color = c1c1c5
selection-background = c1c1c5
selection-foreground = 0a0a17

palette = 0=#0a0a17
palette = 1=#6F1217
palette = 2=#5A1E25
palette = 3=#8E141A
palette = 4=#AD151B
palette = 5=#901B23
palette = 6=#AF1A23
palette = 7=#c1c1c5
palette = 8=#59596d
palette = 9=#6F1217
palette = 10=#5A1E25
palette = 11=#8E141A
palette = 12=#AD151B
palette = 13=#901B23
palette = 14=#AF1A23
palette = 15=#c1c1c5
