# Appearance
gappih = 0
gappiv = 0
gappoh = 0
gappov = 0
scratchpad_width_ratio = 0.8
scratchpad_height_ratio = 0.9

borderpx = 0
rootcolor = 0x201b14ff
bordercolor = 0x201b14ff
focuscolor = 0xfad060FF
maximizescreencolor = 0x89aa61ff
urgentcolor = 0xad401fff
scratchpadcolor = 0x516c93ff
globalcolor = 0xb153a7ff
overlaycolor = 0x14a57cff