# key name refer to `xev` or `wev` command output,
bind = SUPER, r, reload_config
bind = Alt, r, spawn, ghostty
bind = Alt, q, killclient,
bind = Alt, space, spawn, rofi -show drun
bind = Alt, o, spawn_shell, ~/dotfiles/nixos/scripts/clean_exit.sh
bind = Alt, V, spawn_shell, copyq toggle
bind = Alt, I, togglefloating

bind = NONE, Print, spawn_shell, grim -g "$(slurp)" - | swappy -f - &
bind = NONE, F1, spawn_shell, ~/dotfiles/nixos/dots/nixboom/.config/waybar/random_wallpaper.sh
bind = NONE, F2, spawn_shell, ~/dotfiles/nixos/scripts/sys_sounds/volume_decrease.sh
bind = NONE, F3, spawn_shell, ~/dotfiles/nixos/scripts/sys_sounds/volume_increase.sh
bind = NONE, F4, spawn_shell, ~/dotfiles/nixos/scripts/sys_sounds/volume_mute.sh
bind = NONE, F5, spawn, playerctl previous
bind = NONE, F6, spawn, playerctl next
bind = NONE, F7, spawn, playerctl play-pause
bind = NONE, F8, spawn_shell, swaylock & playerctl pause

# switch window focus
bind = Alt, Tab, focusstack, next
bind = Alt, A, focusdir, left
bind = Alt, D, focusdir, right
bind = Alt, W, focusdir, up
bind = Alt, S, focusdir, down

# swap window
bind = Alt+SHIFT, W, exchange_client, up
bind = Alt+SHIFT, S, exchange_client, down
bind = Alt+SHIFT, A, exchange_client, left
bind = Alt+SHIFT, D, exchange_client, right

# monitor switch
bind = Alt+SHIFT, j, focusmon, left
bind = Alt+SHIFT, l, focusmon, right
bind = Alt+SHIFT, i, focusmon, up
bind = Alt+SHIFT, k, focusmon, down

bind = Alt+CTRL,j,tagmon,left
bind = Alt+CTRL,l,tagmon,right
bind = Alt+CTRL,i,tagmon,up
bind = Alt+CTRL,k,tagmon,down



# switch window status
bind = Alt, g, toggleglobal,
bind = Alt, Tab, toggleoverview,
bind = Alt+CTRL, f, togglefullscreen,
bind = Alt+SHIFT, f, togglefakefullscreen,
#bind = Alt, T, toggleoverlay,
#bind = Alt, X, minimized,
#bind = Alt+SHIFT, X, restore_minimized

#floatin/global
bind = SUPER,left,movewin,-10,+0
bind = SUPER,right,movewin,+10,+0
bind = SUPER,up,movewin,+0,-10
bind = SUPER,down,movewin,+0,+10

# switch layout
bind = Alt, M, switch_layout


# workspace switch
bind = Alt, 1, view, 1, 0
bind = Alt, 2, view, 2, 0
bind = Alt, 3, view, 3, 0
bind = Alt, 4, view, 4, 0
bind = Alt, 5, view, 5, 0
bind = Alt, 6, view, 6, 0
bind = Alt, 7, view, 7, 0
bind = Alt, 8, view, 8, 0
bind = Alt, 9, view, 9, 0

# tile swapping
bind = Alt+SHIFT, 1, tag, 1, 0
bind = Alt+SHIFT, 2, tag, 2, 0
bind = Alt+SHIFT, 3, tag, 3, 0
bind = Alt+SHIFT, 4, tag, 4, 0
bind = Alt+SHIFT, 5, tag, 5, 0
bind = Alt+SHIFT, 6, tag, 6, 0
bind = Alt+SHIFT, 7, tag, 7, 0
bind = Alt+SHIFT, 8, tag, 8, 0
bind = Alt+SHIFT, 9, tag, 9, 0

#resizewin
bind=Alt+CTRL,up,resizewin,+0,-50
bind=Alt+CTRL,down,resizewin,+0,+50
bind=Alt+CTRL,left,resizewin,-50,+0
bind=Alt+CTRL,right,resizewin,+50,+0

# Mouse Button Bindings
mousebind = Alt, btn_left, moveresize, curmove
mousebind = Alt, btn_right, moveresize, curresize