foreground         #c6c7c8
background         #1b2125
background_opacity 1.0
cursor             #c6c7c8

active_tab_foreground     #1b2125
active_tab_background     #c6c7c8
inactive_tab_foreground   #c6c7c8
inactive_tab_background   #1b2125

active_border_color   #c6c7c8
inactive_border_color #1b2125
bell_border_color     #88857B

color0       #1b2125
color8       #626f78
color1       #88857B
color9       #88857B
color2       #989386
color10      #989386
color3       #A29D8F
color11      #A29D8F
color4       #B0AA9B
color12      #B0AA9B
color5       #B7B1A1
color13      #B7B1A1
color6       #BAB4A5
color14      #BAB4A5
color7       #c6c7c8
color15      #c6c7c8
