{inputs,...}:{
  flake.nixosModules.system = {pkgs, ... }: {
    environment.systemPackages = with pkgs; [
      ly
      efibootmgr
      os-prober  
      curl
      git
      gh
      libnotify
      brightnessctl
      borgbackup
      ntfs3g
      xdg-desktop-portal-gtk
      xdg-desktop-portal-wlr
      qbittorrent
      starship
      bash
      fish
      zoxide
      emacs
      yazi
      eza
      bat
      bottom
      cmatrix
      fastfetch
      fd
      viu
      statix
      gnomeExtensions.auto-power-profile
      ];
    fonts.packages = with pkgs; with nerd-fonts; [
      fira-code
      droid-sans-mono
      dejavu-sans-mono      
    ];
   };
}